require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe AuthorsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Author. As you add validations to Author, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    { surname: 'Claus', firstname: 'Hugo', birthdate: Date.new(1950, 7, 2), sex: 1, title: ''}
  }

  let(:invalid_attributes) {
    { created_at: Time.now, updated_at: Time.now }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AuthorsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all authors as @authors" do
      author = Author.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:authors)).to eq([author])
    end
  end

  describe "GET #show" do
    it "assigns the requested author as @author" do
      author = Author.create! valid_attributes
      get :show, params: {id: author.to_param}, session: valid_session
      expect(assigns(:author)).to eq(author)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Author" do
        expect {
          post :create, params: {author: valid_attributes}, session: valid_session
        }.to change(Author, :count).by(1)
      end

      it "assigns a newly created author as @author" do
        post :create, params: {author: valid_attributes}, session: valid_session
        expect(assigns(:author)).to be_a(Author)
        expect(assigns(:author)).to be_persisted
      end

    end

    context "with invalid params" do
      xit "assigns a newly created but unsaved author as @author" do
        post :create, params: {author: invalid_attributes}, session: valid_session
        expect(assigns(:author)).to be_a_new(Author)
      end

    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested author" do
        author = Author.create! valid_attributes
        put :update, params: {id: author.to_param, author: new_attributes}, session: valid_session
        author.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested author as @author" do
        author = Author.create! valid_attributes
        put :update, params: {id: author.to_param, author: valid_attributes}, session: valid_session
        expect(assigns(:author)).to eq(author)
      end
      
    end

    context "with invalid params" do
      it "assigns the author as @author" do
        author = Author.create! valid_attributes
        put :update, params: {id: author.to_param, author: invalid_attributes}, session: valid_session
        expect(assigns(:author)).to eq(author)
      end

    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested author" do
      author = Author.create! valid_attributes
      expect {
        delete :destroy, params: {id: author.to_param}, session: valid_session
      }.to change(Author, :count).by(-1)
    end

  end

end
